# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  schedule:
    - cron: 49 3 13 * *
  workflow_dispatch: null

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir release
          echo "some file content" > ./release/jojo
          echo "some other content" > ./release/momo

      - name: Release
        shell: bash
        run: |
          gh release create `date --iso-8601` ./release/* -R $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
