# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  schedule:
    - cron: 49 3 13 * *
  workflow_dispatch: null

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: fawazahmed0/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          swap-size-mb: 4096
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Install dependencies
        shell: bash
        run: |
          npm i
          npx playwright install --with-deps
      # Runs a set of commands using the runners shell
      - name: Get Android Apks
        run: |
          node android-extract.js

      # Runs a set of commands using the runners shell
      - name: Fetch links.json
        run: |
          node downloader.js

      - name: Release
        shell: bash
        run: |
          gh release create `date --iso-8601` ./release/* -R $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
